version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes

  celeryworker:
    image: 'celery:5.1.2'
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - SERVER_NAME=localhost
      - SERVER_HOST=http://localhost
    build:
      context: .
      dockerfile: celery.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}