version: "3"

services:
  app:
    depends_on:
      - db
    volumes:
      - ./data/media/static:/vol/web/static
      - ./data/media/media:/vol/web/media


  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  celeryworker:
    depends_on:
      - db
    volumes:
      - ./data/media/static:/vol/web/static
      - ./data/media/media:/vol/web/media