# Generated by Django 3.2.6 on 2021-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20211207_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shirtNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
