# Generated by Django 3.2.6 on 2021-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_player_shirtnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
