# Generated by Django 3.2.6 on 2022-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20211207_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
    ]
