# Generated by Django 3.2.6 on 2022-01-02 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_alter_match_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.IntegerField(default=0)),
            ],
        ),
    ]
