# Generated by Django 3.2.6 on 2022-01-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_seasoninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('away_goals', models.IntegerField(blank=True, default=None, null=True)),
                ('home_goals', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.score'),
        ),
    ]
