# Generated by Django 3.2.6 on 2022-01-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20220102_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.team'),
        ),
    ]
