# Generated by Django 3.2.6 on 2022-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_alter_score_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
