# Generated by Django 3.2.6 on 2022-01-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20220108_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
