# Generated by Django 3.2.6 on 2022-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20220114_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crest',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
