# Generated by Django 3.2.6 on 2021-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user1_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user2_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
