# Generated by Django 3.2.6 on 2021-12-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20211207_1525'),
        ('bet', '0002_auto_20211206_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.match'),
        ),
    ]
