# Generated by Django 3.2.6 on 2021-12-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_auto_20211228_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betscorer',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorers', to='bet.bet'),
        ),
    ]
