# Generated by Django 3.2.6 on 2021-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_alter_betscorer_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
    ]
