# Generated by Django 3.2.6 on 2021-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0006_bet_is_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
