# Generated by Django 3.2.6 on 2022-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0007_bet_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='is_draw',
        ),
        migrations.AddField(
            model_name='bet',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
