# Generated by Django 3.2.6 on 2022-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0009_bet_bet_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
