# Generated by Django 3.2.3 on 2021-05-31 12:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Server connection')),
                ('port', models.IntegerField(verbose_name='Connection port')),
                ('username', models.CharField(max_length=255, verbose_name='User connection name')),
                ('password', models.CharField(max_length=255, verbose_name='Connection password')),
                ('use_tls', models.BooleanField(max_length=255, verbose_name='Is connection TLS?')),
                ('fail_silently', models.BooleanField(default=True, verbose_name='Fail silently for SMTP connection')),
                ('from_email', models.CharField(max_length=255, null=True, verbose_name='Email from')),
                ('default', models.BooleanField(default=False, verbose_name='Is default connection')),
            ],
        ),
        migrations.CreateModel(
            name='AsyncMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(max_length=255, verbose_name='Body email')),
                ('from_email', models.CharField(max_length=255, verbose_name='From email')),
                ('to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('send_time', models.DateTimeField(editable=False, null=True, verbose_name='Send time')),
                ('status', models.IntegerField(choices=[(1, 'Email will be sending'), (2, 'Email will be sending'), (3, 'Email sending is fail'), (4, 'Email is done')], default=1, verbose_name='Status')),
                ('error_message', models.TextField(null=True, verbose_name='Error message')),
                ('priority', models.IntegerField(default=2, verbose_name='Sending priority')),
                ('hash', models.CharField(editable=False, max_length=255, null=True, verbose_name='Hash email string')),
                ('body_text', models.TextField(null=True, verbose_name='Text version')),
                ('batch', models.BooleanField(default=False, null=True, verbose_name='Send email in batch process')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.smtpserver')),
            ],
        ),
    ]
