# Generated by Django 3.2.3 on 2021-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asyncmail',
            options={'verbose_name': 'Async mail', 'verbose_name_plural': 'Async mails'},
        ),
        migrations.AlterModelOptions(
            name='smtpserver',
            options={'verbose_name': 'Smtp server', 'verbose_name_plural': 'Smtp servers'},
        ),
        migrations.AddField(
            model_name='asyncmail',
            name='reply_to',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Reply to'),
        ),
    ]
