# Generated by Django 3.2.3 on 2021-06-01 15:05

import core.models
import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'email_already_used'}, max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Name')),
                ('surname', models.CharField(default='', max_length=64, verbose_name='Surname')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=core.models.safe_file_path, validators=[core.validators.validate_file_size], verbose_name='Avatar')),
                ('document_front', models.FileField(blank=True, default=None, null=True, upload_to=core.models.safe_file_path, validators=[core.validators.validate_file_size], verbose_name='Document front')),
                ('document_back', models.FileField(blank=True, default=None, null=True, upload_to=core.models.safe_file_path, validators=[core.validators.validate_file_size], verbose_name='Document back')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Is email verified?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Use this option for create Staff', verbose_name='Is staff?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=64, verbose_name='City')),
                ('street', models.CharField(default='', max_length=64, verbose_name='Street')),
                ('postal_code', models.CharField(default='', max_length=10, verbose_name='Postal code')),
                ('state', models.CharField(default='', max_length=64, verbose_name='State')),
                ('country', models.CharField(default='', max_length=64, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
