# Generated by Django 3.2.9 on 2021-11-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
    ]
