# Generated by Django 3.2.6 on 2022-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_clients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
